# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_module": "core.ipynb",
         "arch_summary": "core.ipynb",
         "min_max_scale": "preprocessing.ipynb",
         "norm": "preprocessing.ipynb",
         "GlobalContrastNorm": "preprocessing.ipynb",
         "ZCAWhitenWrapper": "preprocessing.ipynb",
         "show_heatmap": "visualize.grad_cam.ipynb",
         "create_batch": "visualize.grad_cam.ipynb",
         "GuidedBackprop": "visualize.grad_cam.ipynb",
         "to_grayscale": "visualize.grad_cam.ipynb"}

modules = ["core.py",
           "transforms.py",
           "visualize.py"]

doc_url = "https://Kshitij09.github.io/fast_impl/"

git_url = "https://github.com/Kshitij09/fast_impl/tree/master/"

def custom_doc_links(name): return None
