# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_module": "00_arch_summary.ipynb",
         "arch_summary": "00_arch_summary.ipynb"}

modules = ["core.py"]

doc_url = "https://Kshitij09.github.io/fast_impl/"

git_url = "https://github.com/Kshitij09/fast_impl/tree/master/"

def custom_doc_links(name): return None
