# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/preprocessing.ipynb (unless otherwise specified).

__all__ = ['min_max_scale', 'GlobalContrastNorm']

# Cell
from fastai2.vision.all import *

# Cell
def min_max_scale(x:Tensor,min=0,max=1):
  return min + ((x-x.min()) * (max-min)) / (x.max()-x.min())

# Cell
class GlobalContrastNorm(Transform):
  """prevents images from having varying contrast
  reference: [Maxout Networks](https://arxiv.org/abs/1302.4389)
  decodes used for `show_batch`.
  Currently it's designed to work with batch of RGB
  images only
  """
  order=11 # Need to be applied after IntToFloatTensor
  def __init__(self,s=1,eps=1e-8,lmbda=0.):
    store_attr(self,'s,eps,lmbda')

  def encodes(self, x:TensorImage):
    contrast = (x.var((1,2,3),keepdim=True)+self.lmbda).sqrt().clamp_(self.eps)
    return self.s * (x - x.mean((1,2,3),keepdim=True)) / contrast

  def decodes(self,x:TensorImage): return min_max_scale(x)